name: branch-live

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  pulumi-preview:
    name: pulumi-preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - './infra'
          # - './infra/aws-oidc'
          # - './infra/policy'
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install deps
        working-directory: ${{ matrix.directory }}
        run: npm install

      - name: auth pulumi cloud
        uses: pulumi/auth-actions@v1
        with:
          organization: pulumi-sandbox-diana
          requested-token-type: urn:pulumi:token-type:access_token:organization
        
      - name: preview stack
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: pulumi-sandbox-diana/cicd-live/dev
          work-dir: ./infra
          comment-on-pr: true
          comment-on-summary: true
          edit-pr-comment: true