name: drift-done
on:
  schedule:
    # Actions schedules runs every 5 minutes.
    # - cron: '*/5 * * * *'

    # Every 24 hours
    - cron: '0 0 5 31 2 ?'
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  drift-detection:
    runs-on: ubuntu-latest
    env:
      INFRA_DIR: './infra-done'
      NODE_VERSION: 22
      PULUMI_ORG: 'pulumi-sandbox-diana'
      PULUMI_STACK: 'pulumi-sandbox-diana/cicd/dev'
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install deps
        working-directory:  ${{ env.INFRA_DIR }}
        run: npm install

      - name: auth pulumi cloud
        uses: pulumi/auth-actions@v1
        with:
          organization: ${{ env.PULUMI_ORG }}
          requested-token-type: urn:pulumi:token-type:access_token:organization
        
      - name: preview resources
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: ${{ env.PULUMI_STACK }}
          work-dir: ${{ env.INFRA_DIR }}
          comment-on-pr: true
          comment-on-summary: true
          edit-pr-comment: true
          expect-no-changes: true
          refresh: true
