name: drift-done
on:
  schedule:
    # Actions schedules runs every 5 minutes.
    # - cron: '*/5 * * * *'

    # Every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  main:
    name: drift detection
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - './infra-done'
          - './infra-done/aws-oidc'
          - './infra-done/aws-cis'
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install deps
        working-directory: ${{ matrix.directory }}
        run: npm install

      - name: auth pulumi cloud
        uses: pulumi/auth-actions@v1
        with:
          organization: pulumi-sandbox-diana
          requested-token-type: urn:pulumi:token-type:access_token:organization
        
      - name: preview resources
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: pulumi-sandbox-diana/cicd/dev
          work-dir: ./infra-done
          policyPacks: aws-cis
          comment-on-pr: true
          comment-on-summary: true
          edit-pr-comment: true
          expect-no-changes: true
          refresh: true