name: main-live

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  pulumi-up:
    runs-on: ubuntu-latest
    env:
      # PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      INFRA_DIR: './infra'
      NODE_VERSION: 22
      # POLICY_DIR: './infra/aws-cis'
      # POLICY_PACK: 'aws-cis'
      PULUMI_ORG: 'pulumi-sandbox-diana'
      PULUMI_STACK: 'pulumi-sandbox-diana/cicd-live/dev'
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install deps infra
        working-directory: ${{ env.INFRA_DIR }}
        run: npm install

      # - name: install deps compliance
      #   working-directory: ${{ env.POLICY_DIR }}
      #   run: npm install

      # - name: auth pulumi cloud
      #   uses: pulumi/auth-actions@v1
      #   with:
      #     organization: ${{ env.PULUMI_ORG }}
      #     requested-token-type: urn:pulumi:token-type:access_token:organization
        
      - name: crud resources
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: ${{ env.PULUMI_STACK }}
          work-dir: ${{ env.INFRA_DIR }}
          # policyPacks: ${{ env.POLICY_PACK }}
          comment-on-pr: true
          comment-on-summary: true
          edit-pr-comment: true
